definitions:
  steps:
    - step: &test
        name: 'Run tests'
        image: 'python:3.6-slim-buster'
        script:
          - pip install -r requirements.txt
          - python -m unittest -v
    - step: &compress
          name: 'Compress package'
          image: 'atlassian/default-image:2'
          script:
            - zip -r release.zip ./ -x ./.git
          artifacts: 
            - release.zip
    - step: &deploy
        name: 'Deploy package'
        image: 'python:3.7.3'
        script:
          - pip install boto3
            # update all deplyments, except test and develop
            # regex is mached from beginning of string
          - python deploy-aws.py release.zip '((?!(development|test)).+|(development|test).+|)$'
pipelines:
  branches:
    restful_api:
      - step: *test
