image:
  name: fabcontrol/images:python3.6
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  # Dockerfile here
  #FROM python:3.6-slim-buster
  #RUN apt-get update
  #RUN apt-get -y install zip libcairo2 libpango-1.0-0 libpangocairo-1.0-0
  #RUN pip install boto3

definitions:
  steps:
    - step: &test
        name: 'Run tests'
        script:
          - pip install -r requirements.txt
          - python -m unittest -v
    - step: &deploy
        name: 'Deploy package'
        script:
          - zip -r release.zip ./ -x ./.git/**\*
            # update all deplyments, except test and develop
            # regex is mached from beginning of string
          - python deploy-aws.py release.zip '((?!(develop|test)).+|(develop|test).+|)$'

pipelines:
  branches:
    aws-live:
      - step: *test
      - step: *deploy
